export const ADD_REVIEW = 'ADD_REVIEW';
export const REMOVE_REVIEW = 'REMOVE_REVIEW'
export const EDIT_REVIEW = 'EDIT_REVIEW'
export const REVIEW_LOADING = 'REVIEW_LOADING'
export const REVIEW_FAILED = 'REVIEW_FAILED'

export const DEALS_ADD = 'DEALS_ADD';
export const DEALS_LOADING = 'DEALS_LOADING'
export const DEALS_FAILED = 'DEALS_FAILED'