export const REVIEW_ADD = 'REVIEW_ADD';
export const REVIEWS_ADD = 'REVIEWS_ADD';
export const REVIEWS_LOADING = 'REVIEWS_LOADING';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';

export const DEAL_ADD = 'DEAL_ADD';
export const DEALS_ADD = 'DEALS_ADD';
export const DEALS_LOADING = 'DEALS_LOADING';
export const DEALS_FAILED = 'DEALS_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FAVORITES_ADD = 'FAVORITES_ADD';
export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';