export const REVIEW_ADD = 'REVIEW_ADD';
export const REVIEW_REMOVE = 'REVIEW_REMOVE'
export const REVIEW_EDIT = 'REVIEW_EDIT'

export const REVIEWS_ADD = 'REVIEWS_ADD'
export const REVIEWS_LOADING = 'REVIEWS_LOADING'
export const REVIEWS_FAILED = 'REVIEWS_FAILED'

export const DEALS_ADD = 'DEALS_ADD';
export const DEALS_LOADING = 'DEALS_LOADING'
export const DEALS_FAILED = 'DEALS_FAILED'